#### Part 1: Importing, merging, and re-structuring data in tidyverse ####

## Set your working directory
# choose the folder containing this file and the data subfolder
setwd()

## Check working directory
getwd()

## Install and load packages
install.packages("tidyverse") # Only do this once
library(tidyverse)
library(lubridate)

## Import data files



## Explore your data
str(ca_generation)
glimpse(ca_generation)
glimpse(ca_imports)

## Merge datasets
ca_energy <- merge(ca_generation, ca_imports, by="datetime")

## Wide vs. long format data: example
ca_generation_long <- gather(ca_generation, key = "variable", value = "value", -datetime)
head(ca_generation_long)

## Wide vs. long format data: exercise



#### Part 2: Data transformation with dplyr ####

## Exercise 1: select()





## Exercise 2: filter()



## Exercise 3: Pipes


## Exercise 4: mutate()



## Exercise 5: group_by() and summarize()



#### Part 3: Data visualization with dplyr ####

## Import data file
gapminder <- read_csv("data/gapminder.csv")
glimpse(gapminder)

## Mini-exercise: subset data to only keep rows from 2007; save as gapminder07


## Example: GDP over life expectancy in 2007
ggplot(gapminder07) + 
    geom_point(aes(x = gdpPercap, y = lifeExp)) + 
    labs(title = "Relationship between life expectancy and GDP per capita in 2007", 
         x = "GDP per capita", y = "Life expectancy")

## Exercise 1: Scatterplot


## Example: Energy generated over time
ca_energy_long %>% 
    group_by(datetime) %>% 
    summarise(value=sum(value)) %>% 
    ggplot() + 
    geom_col(aes(x=datetime, y=value)) + 
    labs(title="Total energy generated, by hour", x="Hour", y="Output (MW)")

## Exercise 2: Hydro power generated over time


## Example: line plot
ca_energy %>%
    ggplot() + 
    geom_line(aes(x=datetime, y=imports)) + 
    labs(title="Energy imports over time", x="Hour", y="Amount imported (MW)")

## Example: line plot with charactersitics modifications
ca_energy %>%
    ggplot() + 
    geom_line(aes(x=datetime, y=imports), size=1.2, col="red") + 
    labs(title="Energy imports over time", x="Hour", y="Amount imported (MW)")

## Example: area plot
ca_energy %>% 
    ggplot() + 
    geom_area(aes(x=datetime, y=wind), fill="darkblue") + 
    labs(title="Hourly wind power generation, Sept 3-9", x="Hour", y="Output (MW)")

## Example: box plot
ca_energy_long %>% 
    ggplot() + 
    geom_boxplot(aes(x=variable, y=value)) + 
    labs(title="Amount of energy generated by each source, Sept 3-9", x="Source type", y="Output (MW)")

## Example: multiple geoms in one plot
ca_energy %>% 
    ggplot() + 
    geom_point(aes(x=datetime, y=large_hydro), col="red") + 
    geom_smooth(aes(x=datetime, y=large_hydro)) + 
    labs(title="Hydroelectric (large) generation per hour, Sept 3-9", x="Hour", y="Output (MW)")

## Exercise 3: Total output per source


## Example: Grouped data with colors
ca_energy_long %>%
    ggplot() + 
    geom_line(aes(x=datetime, y=value, group=variable, col=variable)) + 
    labs(title="Output by energy source over time", subtitle="Hourly data from September 3-9, 2018", x="Hour", y="Output (MW)")

## Exercise 4: Colors and fill


## Example: Energy use by day, position dodge
ca_energy_long %>% 
    mutate(date=date(datetime)) %>% 
    group_by(date, variable) %>% 
    summarize(value=sum(value)) %>% 
    ggplot() + 
    geom_col(aes(x=date, y=value, group=variable, fill=variable), position="dodge") + 
    labs(title="Energy use by day", x="Day", y="Output (MW)")

## Example: Grouped data with sizes
gapminder07 %>% 
    ggplot() + 
    geom_point(aes(x=log(gdpPercap), y=lifeExp, size=pop, col=continent)) + 
    labs(title="Life expectancy as a function of GDP per capita in 2007", 
         x="Logged GDP per capita", y="Life expectancy")

## Exercise 5: Average hourly output by source


## Example: Facets (comparing generation patterns)
ca_energy_long %>% 
    ggplot() + 
    geom_line(aes(x = datetime, y = value)) + 
    facet_wrap(~variable, scales="free") + 
    labs(title="Generation over time, by energy source", subtitle="Hourly data from September 3-9, 2018", 
         x="Hour", y="Output (MW)")

## Exercise 6: Facets

